= HOWTO: start service as docker container

== Cleaning previosly started container

[source,shell]
----
docker ps -a
docker kill vuzoll_ingest_vk_data; docker rm vuzoll_ingest_vk_data
----

== Configuration parameters

Following environment variable are available for global service configuration:

MONGO_DATABASE_NAME - mongodb database name to use (default is vuzoll)

MONGO_AUTH_DATABASE_NAME - mongodb database name used for authentication (default is admin)

MONGO_HOST - host of mongodb instance (default is vuzoll_mongo)

MONGO_PORT - port of mongodb instance (default is 27017)

MONGO_USERNAME - username for authentication to mongodb (default is ingestVkService)

MONGO_PASSWORD - password for authentication to mongodb

VK_API_ACCESS_TOKEN, VK_API_USER_ID - VK API credentials

VK_API_REQUEST_SIZE - number of records to ingest in one request (default is 1000)

ROOT_LOG_LEVEL - logging level for third-party libraries (default is INFO)

VUZOLL_LOG_LEVEL - logging level for service code (default is INFO)

== Unauthorized start

[source,shell]
----
docker pull vuzoll/vuzoll-ingest-vk-data:?TAG
docker run -dit --name vuzoll_ingest_vk_data --link vuzoll_mongo -v /logs:/logs -e MONGO_PASSWORD=?MONGO_PASSWORD -p 28001:8080 vuzoll/vuzoll-ingest-vk-data:?TAG
----

== Authorized start

If you want to authorize your VK API access to be able to ingest secured data do the following:

- Go to https://oauth.vk.com/authorize?client_id=5763182&scope=friends,offline&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token
- You will be redirected to URL like https://oauth.vk.com/blank.html#access_token=ACCESS_TOKEN&expires_in=0&user_id=USER_ID
- Copy ACCESS_TOKEN and USER_ID values
- Use following docker config command to start

[source,shell]
----
docker pull vuzoll/vuzoll-ingest-vk-data:?TAG
docker run -dit --name vuzoll_ingest_vk_data --link vuzoll_mongo -v /logs:/logs -e MONGO_PASSWORD=?MONGO_PASSWORD -e VK_API_ACCESS_TOKEN=ACCESS_ID -e VK_API_USER_ID=USER_ID -p 28001:8080 vuzoll/vuzoll-ingest-vk-data:?TAG
----